# Generated by Django 5.2.7 on 2025-12-05 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('boards', '0002_alter_board_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_users',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.users'),
        ),
    ]
