# Generated by Django 5.2.7 on 2025-12-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
