# Generated by Django 6.0 on 2025-12-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_users_user'),
        ('boards', '0004_boards_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board_users',
            unique_together={('user_id', 'board_id')},
        ),
    ]
