# Generated by Django 5.2.7 on 2025-12-05 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stickers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(max_length=100)),
                ('color', models.TextField(max_length=6)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('z_index', models.IntegerField(default=0)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.boards')),
            ],
        ),
    ]
